name: Python Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4.1.1
    - name: Set up Python 3.11
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip        
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint black isort        
    - name: Lint code
      run: |
        find . -type f -name "*.py" | xargs pylint
        find . -type f -name "*.py" | xargs black --check
        find . -type f -name "*.py" | xargs isort --check
